### ISSUE TITLE
there is no use group for manage admin

### ISSUE THREAD

**Issue by csgentr** [Summer-16/CSGO-VMPanel#28] opened 2021-01-12 08:45 UTC
hi first of all

thanks for this great script, its working like a charm !

manage vip side working very well I use for all vip and admins groups and there is "use group" section in manage vip side.

but there is no use group on manage admin. could u add there. cause I "use group" admin_groups.cfg for admins..

thank you.

**Comment by Summer-16** [comment] 2021-01-13 18:07
Hi thanks for the suggestion, 
I will definitely look into it, but it may be a bit delayed because current due to some reasons i am unable to find time for personal projects.
But i can assure you about this feature coming in next version.

**Comment by Summer-16** [comment] 2021-02-14 12:44
Added feature in Commit 34ecea08a955c0eb24cd0fb37bf449f54c6fb6ee.
Check, verify and provide feedback.

Thank you.

**Comment by csgentr** [comment] 2021-02-14 14:05
hi @Summer-16 thanks again. I check it quickly.. 

when I just want to use group its giving error "flags cannot be empty" 

I could not use just group name for manageadmin side but vip side working very well

**Comment by csgentr** [comment] 2021-02-14 14:08
and when I want to remove admin its works but page is stuck. I show u a pic

https://imgur.com/vWopmMT

**Comment by Summer-16** [comment] 2021-02-14 14:15
It may be due to some missing check I will update it ASAP.

**Comment by Summer-16** [comment] 2021-02-14 16:41
> hi @Summer-16 thanks again. I check it quickly..
> 
> when I just want to use group its giving error "flags cannot be empty"
> 
> I could not use just group name for manageadmin side but vip side working very well

-----------------------

Just verified on my end working fine, https://www.awesomescreenshot.com/video/2751261?key=c3ae112f881b76594e624e3331c1c3ac

All tho the loader issue was there which is fixed in the new commit.

**Comment by csgentr** [comment] 2021-02-14 18:32
now its work very well but now another problem with this, its write to database admin but in admins_simple.ini not

when I want to use View and Manage Admin its giving me error  TypeError: Cannot read property 'length' of undefined
:(

**Comment by Summer-16** [comment] 2021-02-26 18:36
I will need some logs and more details on it.
Can you provide logs from the node server's console as well as what entry is in your table

**Comment by Summer-16** [comment] 2021-03-20 16:53
No response from the author, Closing for now.
Reopen if help required, Otherwise I assume the issue is resolved.

**Closed by Summer-16** 2021-03-20 16:53 UTC
